In [1]:
import pandas as pd

In [2]:
original_data = pd.read_excel('/content/reduced_data.xlsx')
original_data.head()

,ID,BHK_raw_quality_score,median_Freq_speed,mean_d_P,dist_Freq_tilt_x,dist_Freq_speed,median_Freq_tilt_y,Space_Between_Words,bandwidth_tilt_x,std_d_P,mean_Pressure,in_Air,BHK_raw_speed_score,std_Density,median_Freq_tremolo,Age,Dysgraphia
0,S0995,25.500000,0.001744,0.130777,0.000498,0.000218,0.003318,1617.671646,0.004491,3.562989,592.221130,0.621097,207.000000,360.244714,0.003316,9,1
1,S0996,35.000000,0.001564,0.039345,0.000910,0.000126,0.003324,1714.428471,0.004954,1.495864,375.740844,0.587173,63.000000,303.268265,0.003233,9,1
2,S0997,31.333333,0.002356,-0.007538,0.000242,0.001056,0.003333,423.105339,0.003083,0.562388,127.736338,0.610327,74.000000,267.878028,0.003295,8,1
3,S1000,31.000000,0.001599,0.030485,0.000604,0.000136,0.003273,2371.746011,0.005016,1.560180,427.952813,0.604755,52.500000,205.989012,0.003344,8,1
4,S1001,22.666667,0.002250,0.025525,0.000704,0.000899,0.003388,926.590647,0.004022,1.788618,319.640759,0.770747,86.333333,230.280797,0.003338,9,1

In [3]:
original_data.head()

,ID,BHK_raw_quality_score,median_Freq_speed,mean_d_P,dist_Freq_tilt_x,dist_Freq_speed,median_Freq_tilt_y,Space_Between_Words,bandwidth_tilt_x,std_d_P,mean_Pressure,in_Air,BHK_raw_speed_score,std_Density,median_Freq_tremolo,Age,Dysgraphia
0,S0995,25.500000,0.001744,0.130777,0.000498,0.000218,0.003318,1617.671646,0.004491,3.562989,592.221130,0.621097,207.000000,360.244714,0.003316,9,1
1,S0996,35.000000,0.001564,0.039345,0.000910,0.000126,0.003324,1714.428471,0.004954,1.495864,375.740844,0.587173,63.000000,303.268265,0.003233,9,1
2,S0997,31.333333,0.002356,-0.007538,0.000242,0.001056,0.003333,423.105339,0.003083,0.562388,127.736338,0.610327,74.000000,267.878028,0.003295,8,1
3,S1000,31.000000,0.001599,0.030485,0.000604,0.000136,0.003273,2371.746011,0.005016,1.560180,427.952813,0.604755,52.500000,205.989012,0.003344,8,1
4,S1001,22.666667,0.002250,0.025525,0.000704,0.000899,0.003388,926.590647,0.004022,1.788618,319.640759,0.770747,86.333333,230.280797,0.003338,9,1

In [4]:
features = ['BHK_raw_quality_score', 'BHK_raw_speed_score', 'median_Freq_speed', 'Space_Between_Words']

In [5]:
dys_df = original_data[original_data['Dysgraphia'] == 1][['ID'] + features + ['Age']]
normal_df = original_data[original_data['Dysgraphia'] == 0][['ID'] + features + ['Age']]
dys_df

,ID,BHK_raw_quality_score,BHK_raw_speed_score,median_Freq_speed,Space_Between_Words,Age
0,S0995,25.500000,207.000000,0.001744,1617.671646,9
1,S0996,35.000000,63.000000,0.001564,1714.428471,9
2,S0997,31.333333,74.000000,0.002356,423.105339,8
3,S1000,31.000000,52.500000,0.001599,2371.746011,8
4,S1001,22.666667,86.333333,0.002250,926.590647,9
...,...,...,...,...,...,...
275,S1376,34.500000,105.500000,0.001715,1033.910155,7
276,S1379,28.500000,201.000000,0.002029,699.553191,11
277,S1383,25.000000,158.500000,0.002119,668.460279,11
278,S1384,25.000000,94.500000,0.002154,75.451084,10
279,S1391,38.500000,73.000000,0.001729,994.645853,9

In [6]:
dysgraphia_people_evolution = pd.DataFrame(columns = list(dys_df.columns) + ['Date'])
dysgraphia_people_evolution.head()

Empty DataFrame
Columns: [ID, BHK_raw_quality_score, BHK_raw_speed_score, median_Freq_speed, Space_Between_Words, Age, Date]
Index: []

In [7]:
import numpy as np
import datetime

learning_rate = 0.1


current_date = datetime.date(2023, 3, 24)
dates = [current_date + datetime.timedelta(days = 30 * i) for i in range(12)]


for id in list(dys_df.ID):
  person = dys_df[dys_df['ID'] == id]
  age = int(person['Age'].values)
  ages = [age] * 12
  

  X_pred = pd.DataFrame(index = range(12), columns = dysgraphia_people_evolution.columns)
  X_pred['Age'], X_pred['Date'], X_pred['ID'] = ages, dates, [id] * 12
  for f in features:
    X_pred.at[0, f] = person[f].values[0]

  
  for i in range(1, 12):
      
      distances = np.sum(np.square(normal_df[features] - X_pred.iloc[i-1][features]), axis=1)
      
      closest_index = np.argmin(distances)
      
      
      diff = normal_df[features].iloc[closest_index] - X_pred.iloc[i-1][features]
      
      
      X_pred.at[i, tuple(features)] = X_pred.iloc[i-1][features] + learning_rate * diff
  dysgraphia_people_evolution = pd.concat([dysgraphia_people_evolution, X_pred], axis = 0)

In [8]:
dysgraphia_people_evolution

,ID,BHK_raw_quality_score,BHK_raw_speed_score,median_Freq_speed,Space_Between_Words,Age,Date
0,S0995,25.5,207.0,0.001744,1617.671646,9,2023-03-24
1,S0995,24.4,206.95,0.001692,1617.569187,9,2023-04-23
2,S0995,23.41,206.905,0.001645,1617.476974,9,2023-05-23
3,S0995,22.519,206.8645,0.001602,1617.393983,9,2023-06-22
4,S0995,21.7171,206.82805,0.001564,1617.31929,9,2023-07-22
...,...,...,...,...,...,...,...
7,S1391,29.109344,67.000414,0.001576,1013.211245,9,2023-10-20
8,S1391,28.24841,66.450373,0.001562,1014.913318,9,2023-11-19
9,S1391,27.473569,65.955336,0.00155,1016.445184,9,2023-12-19
10,S1391,26.776212,65.509802,0.001538,1017.823864,9,2024-01-18
11,S1391,26.148591,65.108822,0.001528,1019.064675,10,2024-02-17

In [9]:
dysgraphia_people_evolution.to_excel('/content/dysgraphic_people_samples.xlsx', index = None)